#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class SillySudoku {
public:
	int countWays(vector <string> board);
};

int ret;
vector<string> g;

bool checkRow(int i){
	set<char> s;
	for (int j = 0; j < 4; j++) s.insert(g[i][j]);
	return s.size() == 4;
}

bool checkCol(int j){
	set<char> s;
	for (int i = 0; i < 4; i++) s.insert(g[i][j]);
	return s.size() == 4;
}

bool checkBox(int i, int j){
	set<char> s;
	s.insert(g[i][j]);	s.insert(g[i][j-1]);
	s.insert(g[i-1][j]); s.insert(g[i-1][j-1]);
	return s.size() == 4;
}

int boi[] = { 1, 1, 3, 3 };
int boj[] = { 1, 3, 1, 3 };

bool check(int i, int j){
	if (j == 3 && !checkRow(i)) return 0;
	if (i == 3 && !checkCol(j)) return 0;
	for (int k = 0; k < 4; k++)
		if (i == boi[k] && j == boj[k] && !checkBox(i, j)) 
			return 0;
	return 1;
}

void rec(int i, int j){
	if (j > 3){
		if (i == 3) {
			ret++;
			return;
		}
		rec(i + 1, 0);
		return;
	}
	if (g[i][j] != '-'){
		if (!check(i, j)) return;
		rec(i, j + 1);
		return;
	}
	for (int nu = 1; nu < 5; nu++){
		g[i][j] = nu + '0';
		if (check(i, j)) rec(i, j + 1);
		g[i][j] = '-';
	}
}

int SillySudoku::countWays(vector <string> board) {
	ret = 0;
	g = board;
	rec(0, 0);
	return ret;
}

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, int p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	SillySudoku *obj;
	int answer;
	obj = new SillySudoku();
	clock_t startTime = clock();
	answer = obj->countWays(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p1 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <string> p0;
	int p1;
	
	{
	// ----- test 0 -----
	string t0[] = {"--21","--34","2143","3412"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 1;
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	string t0[] = {"--1-","--1-","----","----"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 0;
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	string t0[] = {"1---","-42-","-3--","----"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 3;
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	string t0[] = {"1---","--1-","-1--","---1"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 18;
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	string t0[] = {"1---","----","----","----"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 72;
	all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING


//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
