#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class LotteryTicket {
public:
	string buy(int price, int b1, int b2, int b3, int b4);
};





string LotteryTicket::buy(int price, int b1, int b2, int b3, int b4) {
	for (int i = 0; i < 2; i++) for (int j = 0; j < 2; j++)
		for (int k = 0; k < 2; k++) for (int p = 0; p < 2; p++){
		if (b1*i + b2*j + b3*k + b4*p == price) return "POSSIBLE";
		}
	return "IMPOSSIBLE";
}

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, int p0, int p1, int p2, int p3, int p4, bool hasAnswer, string p5) {
	cout << "Test " << testNum << ": [" << p0 << "," << p1 << "," << p2 << "," << p3 << "," << p4;
	cout << "]" << endl;
	LotteryTicket *obj;
	string answer;
	obj = new LotteryTicket();
	clock_t startTime = clock();
	answer = obj->buy(p0, p1, p2, p3, p4);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << "\"" << p5 << "\"" << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << "\"" << answer << "\"" << endl;
	if (hasAnswer) {
		res = answer == p5;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	}
	else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	}
	else if (hasAnswer) {
		cout << "Match :-)" << endl;
	}
	else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;

	int p0;
	int p1;
	int p2;
	int p3;
	int p4;
	string p5;

	{
		// ----- test 0 -----
		p0 = 10;
		p1 = 1;
		p2 = 5;
		p3 = 10;
		p4 = 50;
		p5 = "POSSIBLE";
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, p3, p4, true, p5) && all_right;
		// ------------------
	}

	{
		// ----- test 1 -----
		p0 = 15;
		p1 = 1;
		p2 = 5;
		p3 = 10;
		p4 = 50;
		p5 = "POSSIBLE";
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, p3, p4, true, p5) && all_right;
		// ------------------
	}

	{
		// ----- test 2 -----
		p0 = 65;
		p1 = 1;
		p2 = 5;
		p3 = 10;
		p4 = 50;
		p5 = "POSSIBLE";
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, p3, p4, true, p5) && all_right;
		// ------------------
	}

	{
		// ----- test 3 -----
		p0 = 66;
		p1 = 1;
		p2 = 5;
		p3 = 10;
		p4 = 50;
		p5 = "POSSIBLE";
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, p3, p4, true, p5) && all_right;
		// ------------------
	}

	{
		// ----- test 4 -----
		p0 = 1000;
		p1 = 999;
		p2 = 998;
		p3 = 997;
		p4 = 996;
		p5 = "IMPOSSIBLE";
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, p3, p4, true, p5) && all_right;
		// ------------------
	}

	{
		// ----- test 5 -----
		p0 = 20;
		p1 = 5;
		p2 = 5;
		p3 = 5;
		p4 = 5;
		p5 = "POSSIBLE";
		all_right = KawigiEdit_RunTest(5, p0, p1, p2, p3, p4, true, p5) && all_right;
		// ------------------
	}

	{
		// ----- test 6 -----
		p0 = 2;
		p1 = 1;
		p2 = 5;
		p3 = 10;
		p4 = 50;
		p5 = "IMPOSSIBLE";
		all_right = KawigiEdit_RunTest(6, p0, p1, p2, p3, p4, true, p5) && all_right;
		// ------------------
	}

	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	}
	else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING


//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
